import React from 'react';
import { 
  Utensils, 
  Brush, 
  Dog, 
  CheckSquare, 
  Home, 
  Car, 
  ShoppingBag, 
  Wrench, 
  Shield, 
  Zap, 
  Droplets, 
  Trash2, 
  Wind, 
  Sun, 
  Moon, 
  Coffee, 
  Book, 
  Camera, 
  Music, 
  Heart,
  Hammer,
  Paintbrush,
  Stethoscope,
  Briefcase,
  GraduationCap,
  Plane,
  Bike,
  Gamepad2,
  Tv,
  Mic,
  Gift,
  Star,
  Bell,
  Calendar,
  Clock,
  MapPin,
  Mail,
  Phone,
  MessageSquare
} from 'lucide-react';

export const TASK_ICONS = [
  { id: 'utensils', icon: <Utensils size={20} />, name: 'Cozinha' },
  { id: 'brush', icon: <Brush size={20} />, name: 'Limpeza' },
  { id: 'dog', icon: <Dog size={20} />, name: 'Pet' },
  { id: 'check-square', icon: <CheckSquare size={20} />, name: 'Geral' },
  { id: 'home', icon: <Home size={20} />, name: 'Casa' },
  { id: 'car', icon: <Car size={20} />, name: 'Carro' },
  { id: 'shopping-bag', icon: <ShoppingBag size={20} />, name: 'Compras' },
  { id: 'wrench', icon: <Wrench size={20} />, name: 'Manutenção' },
  { id: 'shield', icon: <Shield size={20} />, name: 'Segurança' },
  { id: 'zap', icon: <Zap size={20} />, name: 'Energia' },
  { id: 'droplets', icon: <Droplets size={20} />, name: 'Água' },
  { id: 'trash', icon: <Trash2 size={20} />, name: 'Lixo' },
  { id: 'wind', icon: <Wind size={20} />, name: 'Ar' },
  { id: 'sun', icon: <Sun size={20} />, name: 'Dia' },
  { id: 'moon', icon: <Moon size={20} />, name: 'Noite' },
  { id: 'coffee', icon: <Coffee size={20} />, name: 'Café' },
  { id: 'book', icon: <Book size={20} />, name: 'Estudo' },
  { id: 'camera', icon: <Camera size={20} />, name: 'Foto' },
  { id: 'music', icon: <Music size={20} />, name: 'Música' },
  { id: 'heart', icon: <Heart size={20} />, name: 'Saúde' },
  { id: 'hammer', icon: <Hammer size={20} />, name: 'Obra' },
  { id: 'paintbrush', icon: <Paintbrush size={20} />, name: 'Pintura' },
  { id: 'stethoscope', icon: <Stethoscope size={20} />, name: 'Médico' },
  { id: 'briefcase', icon: <Briefcase size={20} />, name: 'Trabalho' },
  { id: 'graduation-cap', icon: <GraduationCap size={20} />, name: 'Escola' },
  { id: 'plane', icon: <Plane size={20} />, name: 'Viagem' },
  { id: 'bike', icon: <Bike size={20} />, name: 'Esporte' },
  { id: 'gamepad', icon: <Gamepad2 size={20} />, name: 'Lazer' },
  { id: 'tv', icon: <Tv size={20} />, name: 'TV' },
  { id: 'mic', icon: <Mic size={20} />, name: 'Áudio' },
  { id: 'gift', icon: <Gift size={20} />, name: 'Presente' },
  { id: 'star', icon: <Star size={20} />, name: 'Importante' },
  { id: 'bell', icon: <Bell size={20} />, name: 'Aviso' },
  { id: 'calendar', icon: <Calendar size={20} />, name: 'Evento' },
  { id: 'clock', icon: <Clock size={20} />, name: 'Tempo' },
  { id: 'map-pin', icon: <MapPin size={20} />, name: 'Local' },
  { id: 'mail', icon: <Mail size={20} />, name: 'Email' },
  { id: 'phone', icon: <Phone size={20} />, name: 'Telefone' },
  { id: 'message', icon: <MessageSquare size={20} />, name: 'Mensagem' },
];

export const getTaskIcon = (iconId?: string) => {
  const iconObj = TASK_ICONS.find(i => i.id === iconId);
  return iconObj ? iconObj.icon : <CheckSquare size={20} />;
};
