import { 
  CheckCircle2, 
  Paintbrush, 
  Trash2, 
  Coffee, 
  Zap, 
  Shield, 
  Wind, 
  Package, 
  Clock, 
  Calendar,
  Settings,
  User,
  Bell,
  Mail,
  Star,
  Heart,
  Wrench,
  Home,
  Camera,
  Music
} from 'lucide-react';

export const AVAILABLE_ICONS = [
  { name: 'CheckCircle2', icon: CheckCircle2 },
  { name: 'Paintbrush', icon: Paintbrush },
  { name: 'Trash2', icon: Trash2 },
  { name: 'Coffee', icon: Coffee },
  { name: 'Zap', icon: Zap },
  { name: 'Shield', icon: Shield },
  { name: 'Wind', icon: Wind },
  { name: 'Package', icon: Package },
  { name: 'Clock', icon: Clock },
  { name: 'Calendar', icon: Calendar },
  { name: 'Settings', icon: Settings },
  { name: 'User', icon: User },
  { name: 'Bell', icon: Bell },
  { name: 'Mail', icon: Mail },
  { name: 'Star', icon: Star },
  { name: 'Heart', icon: Heart },
  { name: 'Wrench', icon: Wrench },
  { name: 'Home', icon: Home },
  { name: 'Camera', icon: Camera },
  { name: 'Music', icon: Music },
];

export const AVAILABLE_COLORS = [
  { name: 'Green', bg: 'bg-green-100', text: 'text-green-600' },
  { name: 'Yellow', bg: 'bg-yellow-100', text: 'text-yellow-600' },
  { name: 'Blue', bg: 'bg-blue-100', text: 'text-blue-600' },
  { name: 'Red', bg: 'bg-red-100', text: 'text-red-600' },
  { name: 'Purple', bg: 'bg-purple-100', text: 'text-purple-600' },
  { name: 'Pink', bg: 'bg-pink-100', text: 'text-pink-600' },
  { name: 'Indigo', bg: 'bg-indigo-100', text: 'text-indigo-600' },
  { name: 'Orange', bg: 'bg-orange-100', text: 'text-orange-600' },
  { name: 'Cyan', bg: 'bg-cyan-100', text: 'text-cyan-600' },
  { name: 'Teal', bg: 'bg-teal-100', text: 'text-teal-600' },
];
